name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.10
      - name: Reproduce bug
        continue-on-error: true
        run: |
             echo "::group::This compilation correctly fails with boost not found"
             em++ main.cpp
             echo "::endgroup::"
             echo "::group::This compilation correctly succeeds with -sUSE_BOOST_HEADERS"
             em++ -sUSE_BOOST_HEADERS main.cpp
             echo "::endgroup::"
             echo "::group::This compilation incorrectly succeeds as USE_BOOST_HEADERS was not given"
             em++ main.cpp
             echo "::endgroup::"